//videos
export const GET_MOVIE_POPULAR = "GET_MOVIE_POPULAR";
export const GET_SERIES_POPULAR = "GET_SERIES_POPULAR";
export const GET_MOVIE_TOP = "GET_MOVIE_TOP";
export const GET_SERIES_TOP = "GET_SERIES_TOP";
export const RESET_VIDEOS = "RESET_VIDEOS";
export const SET_LOADING = "SET_LOADING";
export const GET_GENRES_MOVIE = "GET_GENRES_MOVIE";
export const GET_GENRES_TV = "GET_GENRES_TV";
export const GET_MOVIE_BY_GENRE = "GET_MOVIE_BY_GENRE";
export const GET_SERIES_BY_GENRE = "GET_SERIES_BY_GENRE";
export const SELECT_GENRE = "SELECT_GENRE";
export const RESET_GENRE = "RESET_GENRE";
export const SEARCH_VIDEOS = "SEARCH_VIDEOS";
export const CHANGE_LISTTYPE = "CHANGE_LISTTYPE";
export const CHANGE_VIDEOTYPE = "CHANGE_VIDEOTYPE";

//video detail
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_SERIES_DETAIL = "GET_SERIES_DETAIL";
export const GET_MOVIE_EXTERNALID = "GET_MOVIE_EXTERNALID";
export const GET_SERIES_EXTERNALID = "GET_SERIES_EXTERNALID";
export const GET_SIMILAR_MOVIE = "GET_SIMILAR_MOVIE";
export const GET_SIMILAR_SERIES = "GET_SIMILAR_SERIES";
export const GET_RECCOMENDATIONS_MOVIE = "GET_RECCOMENDATIONS_MOVIE";
export const GET_RECCOMENDATIONS_SERIES = "GET_RECCOMENDATIONS_SERIES";
export const GET_TRAILERS_MOVIE = "GET_TRAILERS_MOVIE";
export const GET_TRAILERS_SERIES = "GET_TRAILERS_SERIES";
